-- =========================================================================
-- UNIFIED TRADING ENGINE SCHEMA
-- =========================================================================
-- Consolidates Crypto, Forex, Indian Stocks, Commodities, and Options
-- into unified tables using an 'asset_class' column.

CREATE TABLE IF NOT EXISTS unified_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    position_id INT NULL,
    asset_class ENUM('CRYPTO', 'INDIAN_STOCK', 'FOREX', 'COMMODITY', 'OPTION') NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    side ENUM('BUY', 'SELL') NOT NULL,
    order_type ENUM('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT') NOT NULL,
    original_quantity DECIMAL(18,8) NOT NULL,
    filled_quantity DECIMAL(18,8) NOT NULL DEFAULT 0,
    remaining_quantity DECIMAL(18,8) NOT NULL,
    price DECIMAL(18,8) NULL,
    trigger_price DECIMAL(18,8) NULL,
    leverage DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    trading_mode ENUM('SPOT', 'FUTURES', 'OPTIONS') NOT NULL DEFAULT 'SPOT',
    status ENUM('PENDING', 'OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED') NOT NULL DEFAULT 'OPEN',
    time_in_force ENUM('GTC', 'IOC', 'FOK', 'PO') NOT NULL DEFAULT 'GTC',
    commission DECIMAL(18,8) NOT NULL DEFAULT 0,
    commission_asset VARCHAR(10) DEFAULT 'USDT',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filled_at DATETIME NULL,
    exchange_order_id VARCHAR(100) NULL,
    reduce_only BOOLEAN NOT NULL DEFAULT FALSE,
    is_maker BOOLEAN NULL,
    fee_rate DECIMAL(8,6) NOT NULL DEFAULT 0.000400,
    INDEX idx_orders_user (user_id),
    INDEX idx_orders_symbol (symbol),
    INDEX idx_orders_status (status),
    INDEX idx_orders_asset_class (asset_class)
);

CREATE TABLE IF NOT EXISTS unified_positions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    asset_class ENUM('CRYPTO', 'INDIAN_STOCK', 'FOREX', 'COMMODITY', 'OPTION') NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    side ENUM('LONG', 'SHORT') NOT NULL,
    entry_price DECIMAL(18,8) NOT NULL,
    quantity DECIMAL(18,8) NOT NULL,
    leverage DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    current_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    unrealised_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    unrealised_pnl_percent DECIMAL(8,4) NOT NULL DEFAULT 0,
    realised_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    margin_used DECIMAL(18,8) NOT NULL DEFAULT 0,
    available_margin DECIMAL(18,8) NOT NULL DEFAULT 0,
    liquidation_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    margin_ratio DECIMAL(6,4) NOT NULL DEFAULT 0,
    take_profit DECIMAL(18,8) NULL,
    stop_loss DECIMAL(18,8) NULL,
    trading_mode ENUM('SPOT', 'FUTURES', 'OPTIONS') NOT NULL DEFAULT 'SPOT',
    entry_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    exit_time DATETIME NULL,
    status ENUM('ACTIVE', 'CLOSING', 'CLOSED', 'LIQUIDATED') NOT NULL DEFAULT 'ACTIVE',
    entry_fee DECIMAL(18,8) NOT NULL DEFAULT 0,
    funding_paid DECIMAL(18,8) NOT NULL DEFAULT 0,
    margin_mode ENUM('ISOLATED', 'CROSS') NOT NULL DEFAULT 'CROSS',
    isolated_margin DECIMAL(18,8) NOT NULL DEFAULT 0,
    mark_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    funding_rate DECIMAL(8,6) NOT NULL DEFAULT 0,
    next_funding_time DATETIME NULL,
    position_mode ENUM('ONE_WAY', 'HEDGE') NOT NULL DEFAULT 'ONE_WAY',
    exit_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    INDEX idx_pos_user (user_id),
    INDEX idx_pos_symbol (symbol),
    INDEX idx_pos_status (status),
    INDEX idx_pos_asset_class (asset_class)
);

CREATE TABLE IF NOT EXISTS unified_trades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    position_id INT NULL,
    asset_class ENUM('CRYPTO', 'INDIAN_STOCK', 'FOREX', 'COMMODITY', 'OPTION') NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    trading_mode ENUM('SPOT', 'FUTURES', 'OPTIONS') NOT NULL DEFAULT 'SPOT',
    entry_order_id INT NULL,
    entry_price DECIMAL(18,8) NOT NULL,
    entry_quantity DECIMAL(18,8) NOT NULL,
    entry_time DATETIME NOT NULL,
    exit_order_id INT NULL,
    exit_price DECIMAL(18,8) NULL,
    exit_quantity DECIMAL(18,8) NULL,
    exit_time DATETIME NULL,
    net_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    pnl_percent DECIMAL(8,4) NOT NULL DEFAULT 0,
    fees_paid DECIMAL(18,8) NOT NULL DEFAULT 0,
    leverage DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    margin_used DECIMAL(18,8) NOT NULL DEFAULT 0,
    duration_seconds INT NULL,
    close_reason VARCHAR(50) NULL,
    INDEX idx_trades_user (user_id),
    INDEX idx_trades_symbol (symbol),
    INDEX idx_trades_asset_class (asset_class)
);

CREATE TABLE IF NOT EXISTS unified_performance (
    user_id INT NOT NULL,
    asset_class ENUM('CRYPTO', 'INDIAN_STOCK', 'FOREX', 'COMMODITY', 'OPTION') NOT NULL,
    total_trades INT NOT NULL DEFAULT 0,
    winning_trades INT NOT NULL DEFAULT 0,
    losing_trades INT NOT NULL DEFAULT 0,
    win_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
    total_realised_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    total_unrealised_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    best_trade_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    worst_trade_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
    largest_winning_trade DECIMAL(18,8) NOT NULL DEFAULT 0,
    largest_losing_trade DECIMAL(18,8) NOT NULL DEFAULT 0,
    avg_win DECIMAL(18,8) NOT NULL DEFAULT 0,
    avg_loss DECIMAL(18,8) NOT NULL DEFAULT 0,
    profit_factor DECIMAL(8,4) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(8,4) NOT NULL DEFAULT 0,
    total_fees_paid DECIMAL(18,8) NOT NULL DEFAULT 0,
    total_volume DECIMAL(24,8) NOT NULL DEFAULT 0,
    last_calculated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    consistency_score INT NOT NULL DEFAULT 0,
    risk_meter INT NOT NULL DEFAULT 0,
    portfolio_health INT NOT NULL DEFAULT 0,
    overall_grade VARCHAR(2) NOT NULL DEFAULT 'F',
    best_asset VARCHAR(20) NULL,
    worst_asset VARCHAR(20) NULL,
    avg_holding_time INT NOT NULL DEFAULT 0,
    PRIMARY KEY(user_id, asset_class)
);

CREATE TABLE IF NOT EXISTS unified_order_fills (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    user_id INT NOT NULL,
    asset_class ENUM('CRYPTO', 'INDIAN_STOCK', 'FOREX', 'COMMODITY', 'OPTION') NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    side ENUM('BUY', 'SELL') NOT NULL,
    quantity DECIMAL(18,8) NOT NULL,
    price DECIMAL(18,8) NOT NULL,
    fee DECIMAL(18,8) NOT NULL DEFAULT 0,
    fee_asset VARCHAR(10) DEFAULT 'USDT',
    is_maker BOOLEAN NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_fills_order (order_id),
    INDEX idx_fills_user (user_id),
    INDEX idx_fills_asset_class (asset_class)
);
